import { err, ok, type Result } from '../shared/result.ts';
import { Day } from './day.ts';
import { InvalidValue } from './errors.ts';

/**
 * Domain identities.
 *
 * Identity is a *domain* concept: an entity has a stable identity from the
 * moment it is created, independent of whether/where it is ever persisted.
 * We model identity as a UUID generated by the domain, wrapped in a typed
 * value object so a `HabitId` can never be mixed up with an `EntryId` (private
 * constructors make the types nominal, not merely structural).
 *
 * A `Habit` needs a surrogate identity because two habits can share every
 * attribute yet be distinct. An `Entry`, by contrast, is uniquely identified
 * by the pair (habit, day) — the domain rule "at most one entry per habit per
 * day" — so its identity is the natural composite `EntryKey`, not a surrogate.
 *
 * Any integer row id a database might use is a persistence artifact that lives
 * entirely inside the infrastructure layer and is never surfaced here.
 *
 * UUID generation uses the web-standard `crypto.randomUUID()` (available both
 * in Node and browsers), so the domain stays free of platform/`node:` imports.
 */
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export class HabitId {
	private constructor(readonly value: string) {}

	/** Mint a fresh identity for a new habit. */
	static generate(): HabitId {
		return new HabitId(globalThis.crypto.randomUUID());
	}

	/** Rehydrate an identity from a stored string, validating its shape. */
	static fromString(value: string): Result<HabitId, InvalidValue> {
		if (!UUID.test(value)) return err(new InvalidValue(`Invalid habit id: "${value}"`));
		return ok(new HabitId(value));
	}

	equals(other: HabitId): boolean {
		return this.value === other.value;
	}

	toString(): string {
		return this.value;
	}
}

/**
 * The natural, composite identity of an entry: the habit it belongs to and the
 * day it records. Two entries are the same entry iff they share this key.
 * No validation is needed as it is assembled from already-valid value objects.
 */
export class EntryKey {
	constructor(
		readonly habitId: HabitId,
		readonly day: Day
	) {}

	equals(other: EntryKey): boolean {
		return this.habitId.equals(other.habitId) && this.day.equals(other.day);
	}

	/** A stable string form, handy as a Map key. */
	toString(): string {
		return `${this.habitId.value}:${this.day.toISO()}`;
	}
}
